config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"
  get "balance_confirm" => "balance_confirm#top"
	post "balance_confirm/show(/:name)" => "balance_confirm#show"
	post "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  resources :incomes
  resources :fixedcosts
  resources :valiablecosts
  resources :income_values
  resources :fixedcost_values
  resources :valiablecost_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
  has_many :fixedcost_value, dependent: :destroy
end

app/models/fixedcost_value.rb
class FixedcostValue < ApplicationRecord
  belongs_to :fixedcost
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_value, dependent: :destroy
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
  belongs_to :income
end

app/models/valiablecost.rb
class Valiablecost < ApplicationRecord
  has_many :valiablecost_value, dependent: :destroy
end

app/models/valiablecost_value.rb
class ValiablecostValue < ApplicationRecord
  belongs_to :valiablecost
end

app/models/variablecost_value.rb
class VariablecostValue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fixedcost_values_controller.rb
class FixedcostValuesController < ApplicationController
  def index
		@fixedcosts = Fixedcost.order(created_at: :asc)
		@fixedcost_values = FixedcostValue.order("year_month asc")
	end

	def show
		@fixedcost_value = FixedcostValue.find(params[:id])
	end

	def new
		@form = Form::FixedcostValueCollection.new
		@fixedcosts = Fixedcost.all
	end

	def edit
		@fixedcost_value = FixedcostValue.find(params[:id])
		@fixedcost = Fixedcost.find(@fixedcost_value.fixedcost_id)
	end

	def create
		@form = Form::FixedcostValueCollection.new(fixedcost_value_collection_params)
    if @form.save
      redirect_to root_path, notice: "商品を登録しました"
    else
      flash.now[:alert] = "商品登録に失敗しました"
      render :new
    end
	end
  private
  def fixedcost_value_collection_params
      params.require(:form_fixedcost_value_collection)
      .permit(fixedcost_values_attributes: [:name, :value, :year_month, :description, :fixedcost_id])
  end
end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  def index
    @fixedcosts = Fixedcost.all
  end

  def show
    @fixedcost = Fixedcost.find(params[:id])
  end

  def new
    @fixedcost = Fixedcost.new
  end

  def edit
    @fixedcost = Fixedcost.find(params[:id])
  end

  def create
    @fixedcost = Fixedcost.new(fixedcost_params)
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました。"
    else
      render "new"
    end
  end

  def update
    @fixedcost = Fixedcost.find(params[:id])
    if @fixedcost.update(fixedcost_params)
      redirect_to @fixedcost, notice: "固定費科目を変更しました。"
    else
      render "new"
    end
  end

  def destroy
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.destroy
    redirect_to fixedcosts_path, notice: "固定費科目を削除しました。"
  end

  private
   def fixedcost_params
    params.require(:fixedcost).permit(:name, :description)
   end
end

app/controllers/income_values_controller.rb
class IncomeValuesController < ApplicationController

	def index
	  @incomes = Income.all
	  @income_values = IncomeValueCollection.all
	end

	def show
	  @income_value = IncomeValue.find(params[:id])
	end

	def new
		@form = Form::IncomeValueCollection.new
	  @income = Income.all
	end

	def edit
		@income_value = IncomeValue.find(params[:id])
		@income = Income.find(@income_value.income_id)
	end

	def create
		@form = Form::IncomeValueCollection.new(income_value_collection_params)
    if @form.save
      redirect_to root_path, notice: "商品を登録しました"
    else
      flash.now[:alert] = "商品登録に失敗しました"
      render :new
    end
	end
  private
    def income_value_collection_params
        params.require(:form_income_value_collection)
        .permit(income_values_attributes: [:name, :value, :year_month, :description, :income_id])
    end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = Income.all
  end

  def show
    @income = Income.find(params[:id])
  end

  def new
    @income = Income.new
  end

  def edit
    @income = Income.find(params[:id])
  end

  def create
		@income = Income.new(income_params)
		if @income.save
		  redirect_to @income, notice: "収入科目を登録しました"
		else
		  render "new"
		end
  end

  def update
    @income = Income.find(params[:id])
		if @income.update(income_params)
			redirect_to @income, notice: "収入科目を登録しました"
		else
			render "new"
		end
  end

  def destroy
    @income = Income.find(params[:id])
		@income.destroy
		redirect_to :incomes, notice: "科目を削除しました。"
  end
  
  private
  
  def income_params
    params.require(:income).permit(:name, :description)
  end
    
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_confirm_helper.rb
module BalanceConfirmHelper
end

app/helpers/baliablecost_helper.rb
module BaliablecostHelper
end

app/helpers/fixedcost_values_helper.rb
module FixedcostValuesHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/variablecost_values_helper.rb
module VariablecostValuesHelper
end

app/views/fixedcost_values/edit.html.erb
<h2>固定費科目　データ修正 </h2>
	<%= form_for @fixedcost_value do |form| %>
	<table>
		<tr>
			<th>登録日</th>
	    <th>名称</th>
	    <th>値</th>
	    <th>備考</th>
	  </tr>
	  <tr>
		  <td><%= form.date_select :year_month,
 						start_year: 2010, end_year: Time.current.year,
 						use_month_numbers: true, discard_day: true %></td>
		  <th><%= @fixedcost.name %></th>
 		  <td><%= form.text_field :value %></td>
 		  <td><%= form.text_field :description %></td>
	  </tr>
	</table>
	<div><%= form.submit %></div>
	<% end %>

app/views/fixedcost_values/index.html.erb
<% require 'active_support/core_ext/numeric/conversions' %>
<h2>固定費科目のデータ登録</h2>
<p>登録年月を設定してください</p>
<%= form_tag({controller: :fixedcost_values, action: :new}, {method: :post}) do %>
	<input type="month" name="year_month">
	<input type="submit">
<% end %>
 
<h2>固定費科目 データ一覧 </h2>
<% if @fixedcost_values.present? %>
<table>
  <tr>
    <th>登録年月</th>
    <th>名称</th>
    <th>値</th>
    <th>備考</th>
		<th>操作</th>
  </tr>
	<% @fixedcost_values.each do |fixedcost_value| %>
	<tr>
		<td><%= fixedcost_value.year_month.strftime('%Y年%m月') %></td>
		<td><%= @fixedcosts.find(fixedcost_value.fixedcost_id).name %></td>
		<td><%= fixedcost_value.value.to_s(:delimited) %> 円</td>
		<td><%= fixedcost_value.description %></td>
		<td>
		<%= link_to "編集", [:edit, fixedcost_value] %> |
		<%= link_to "削除", fixedcost_value, method: :delete,
			data: { confirm: "本当に削除しますか？"} %>
		</td>
	</tr>
	<% end %>
</table>
<% else %>
	<p>登録されているデータがありません。</p>
<% end %>

app/views/fixedcost_values/new.html.erb
<h1>固定費登録</h1>
<table>
  <tr>
    <th>日付</th>
    <th>収入科目</th>
    <th>金額</th>
    <th>詳細</th>
  </tr>
  <%= form_with model: @form, url: fixedcost_values_path, local:true do |form| %>
    <%= form.fields_for :fixedcost_values do |f| %>
      <tr>
        <td><%= f.date_field :year_month %></td>
        <td><%= f.collection_select :fixedcost_id, @fixedcosts, :id, :name, include_blank: "選択して下さい" %></td>
        <td><%= f.text_field :value %>円</td>
        <td><%= f.text_field :description %></td>
      </tr>
    <% end %>
    <%= form.submit %>
  <% end %>
</table>