config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  post "income_values/new(/:name)" => "income_values#new"
  post "fixedcost_values/new(/:name)" => "fixedcost_values#new"
  post "variablecost_values/new(/:name)" => "variablecost_values#new"
  get "balance_confirm" => "balance_confirm#top"
	post "balance_confirm/show(/:name)" => "balance_confirm#show"
	post "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  resources :incomes
  resources :fixedcosts
  resources :valiablecosts
  resources :income_values
  resources :fixedcost_values
  resources :valiablecost_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
  has_many :fixedcost_value, dependent: :destroy
end

app/models/fixedcost_value.rb
class FixedcostValue < ApplicationRecord
  belongs_to :fixedcost
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_value, dependent: :destroy
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
  belongs_to :income
end

app/models/valiablecost.rb
class Valiablecost < ApplicationRecord
  has_many :valiablecost_value, dependent: :destroy
end

app/models/valiablecost_value.rb
class ValiablecostValue < ApplicationRecord
  belongs_to :valiablecost
end

app/models/variablecost_value.rb
class VariablecostValue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  def index
    @fixedcosts = Fixedcost.all
  end

  def show
    @fixedcost = Fixedcost.find(params[:id])
  end

  def new
    @fixedcost = Fixedcost.new
  end

  def edit
    @fixedcost = Fixedcost.find(params[:id])
  end

  def create
    @fixedcost = Fixedcost.new(fixedcost_params)
    if @fixedcost.save
      redirect_to @fixedcost, notice: "固定費科目を登録しました。"
    else
      render "new"
    end
  end

  def update
    @fixedcost = Fixedcost.find(params[:id])
    if @fixedcost.update(fixedcost_params)
      redirect_to @fixedcost, notice: "固定費科目を変更しました。"
    else
      render "new"
    end
  end

  def destroy
    @fixedcost = Fixedcost.find(params[:id])
    @fixedcost.destroy
    redirect_to fixedcosts_path, notice: "固定費科目を削除しました。"
  end

  private
   def fixedcost_params
    params.require(:fixedcost).permit(:name, :description)
   end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = Income.all
  end

  def show
    @income = Income.find(params[:id])
  end

  def new
    @income = Income.new
  end

  def edit
    @income = Income.find(params[:id])
  end

  def create
		@income = Income.new(income_params)
		if @income.save
		  redirect_to @income, notice: "収入科目を登録しました"
		else
		  render "new"
		end
  end

  def update
    @income = Income.find(params[:id])
		if @income.update(income_params)
			redirect_to @income, notice: "収入科目を登録しました"
		else
			render "new"
		end
  end

  def destroy
    @income = Income.find(params[:id])
		@income.destroy
		redirect_to :incomes, notice: "科目を削除しました。"
  end
  
  private
  
  def income_params
    params.require(:income).permit(:name, :description)
  end
    
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/valiablecosts_controller.rb
class ValiablecostsController < ApplicationController
  def index
    @valiablecosts = Valiablecost.all
  end

  def show
    @valiablecost = Valiablecost.find(params[:id])
  end

  def new
    @valiablecost = Valiablecost.new
  end

  def edit
    @valiablecost = Valiablecost.find(params[:id])
  end

  def create
    @valiablecost = Valiablecost.new(valiablecost_params)
    if @valiablecost.save
      redirect_to @valiablecost, notice: "変動費科目を登録しました。"
    else
      render "new"
    end
  end

  def update
    @valiablecost = Valiablecost.find(params[:id])
    if @valiablecost.update(valiablecost_params)
      redirect_to @valiablecost, notice: "変動費科目を変更しました"
    else
      render "new"
    end
  end

  def destroy
    @valiablecost = Valiablecost.find(params[:id])
    @valiablecost.destroy
    redirect_to valiablecosts_path, notice: "変動費科目を削除しました。"
  end

  private

  def valiablecost_params
    params.require(:valiablecost).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_confirm_helper.rb
module BalanceConfirmHelper
end

app/helpers/baliablecost_helper.rb
module BaliablecostHelper
end

app/helpers/fixedcost_values_helper.rb
module FixedcostValuesHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/variablecost_values_helper.rb
module VariablecostValuesHelper
end

app/views/valiablecosts/destroy.html.erb
<h1>Baliablecost#destroy</h1>
<p>Find me in app/views/baliablecost/destroy.html.erb</p>

app/views/valiablecosts/edit.html.erb
<h2>変動費科目編集</h2>
<%= form_with model: @valiablecost, local:true do |f| %>
	<%= render "incomes/form", f: f %>
	<div><%= f.submit %></div>
<% end %>

app/views/valiablecosts/index.html.erb
<h2>変動費科目一覧</h2>

<%= link_to "変動費科目の新規登録", new_valiablecost_path %>

<% if @valiablecosts.present? %>
<table>
	<thead>
		<tr>
			<th>科目名</th>
			<th>備考</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @valiablecosts.each do |valiablecost| %>
			<tr>
				<td><%= valiablecost.name %></td>
				<td><%= valiablecost.description %></td>
				<td>
				<%= link_to "編集", edit_valiablecost_path(valiablecost.id) %>
				<%= link_to "削除", valiablecost_path(valiablecost.id), method: :delete, data: { confirm: "本当に削除しますか？"} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% else %>
	<p>登録されている変動費科目がありません。</p>
<% end %>

app/views/valiablecosts/new.html.erb
<h2>変動費科目登録</h2>
<%= form_with  model: @valiablecost, local:true do |f| %>
	<%= render "incomes/form", f: f %>
	<div><%= f.submit %></div>
<% end %>

app/views/valiablecosts/show.html.erb
<h2>変動費科目の詳細</h2>
 
<%= link_to "編集", edit_valiablecost_path %>
<%= link_to "変動費科目一覧へ戻る", valiablecosts_path %>
 
<table>
 
	<tr>
    <th>名称</th>
    <td><%= @valiablecost.name %></td>
  </tr>
 
	<tr>
		<th>説明</th>
		<td><%= @valiablecost.description %></td>
	</tr>
</table>